### ISSUE TITLE
verified now?

### ISSUE THREAD

**Issue by karlp** [Drachenkaetzchen/carambola2-eagle#1]
http://8devices.com/community/viewtopic.php?f=13&t=399 implies that his is now a verified footprint?

**Comment by Drachenkaetzchen** [comment]
More or less, yes. I haven't personally made a board so far, but according to that forum user as well as my personal test with printed out paper and placing the module on top of it: Yes, it should work.

**Comment by karlp** [comment]
you could update the README.md file then :)
